### ISSUE TITLE
Building wheel for opencv-python (pyproject. toml) did not run successfully.

### ISSUE THREAD

**Issue by jonneymendoza** [tomshaffner/PiThermalCam#29]
Hi, i am trying to install a python library on my raspberry pi 3 b device  and i get this error after waiting a number of hours:

```me@raspberrypi: ~
File Edit Tabs Help
Note: class cv::detail: :GraphcutSeamFinder has more than 1 base class (not supported by Python C extensions)
Bases: cv::detail::GraphCutSeamFinderBase, cv::detail::Seanfinder
Only the first base class will be used
98%] Built target gen_opencv_python_source
98x] Building cxx object modules/python3/CMakeFiles/opencv_ python3.dir/_/src2/cv2.cpp.o
c++: fatal error: killed signal terminated program cclplus
compilation terminated.
gmake[2]: "" [ modu les/ python3/CMakeFi les/opencv _ python3.dir/build.make:76: modules/python3/CMakeFi les/opencv _python:
dir/ _ /src2/cv2.cpp.o] Error 1
gmake[1]: """ [CHakeFiles/Nakefile2:2216: modules/ python3/CHakeFi les/opencv_python3.dir/all] Error 2
gmake: """ [Makefile:166: all] Error 2
Traceback (most recent call last):
File "/tmp/pip-build-env-afnllk7p/over lay/ lib/python3.9/ site-packages/skbuild/setuptools_ wrap.py", line 640, in set
cmkr.make(make _args, install_target=cmake_installtarget, env-env)
File "/tmp/pip-build-env-afnllk7p/overlay/ lib/python3.9/site-packages/skbuild/cmaker.py". line 684, in make
self . make _impl(clargs=clargs, config=config, source_ dir=source _dir, installtarget=installtarget, env-env)
File "/tmp/pip-build-env-afnl lk?p/overlay/lib/python3.9/site-packages/skbuild/cmaker.py". line 715. in make_impl
raise SKBuildError(
An error occurred while building with CMake.
Command:
cmake --build . --target install --config Release --
Install target:
install
Source directory:
/tmp/pip-install-3rgbddoa/opencv-python _a5579075d46e4d1a9494966edbd90a64
working directory:
/tmp/pip-install- 3rgbddoa/opencv-python a5579075d4 6e1d1a9494966edbd90a64/ skbui ld/linux-armv7 l-3.9/cmake-bui ld
Please check the install target is valid and see CMake's output for more information.
error: subprocess-exited-with-error
Building wheel for opencv-python (pyproject. toml) did not run successfully.
exit code:
See above for output
note: This error originates from a subprocess, and is likely not a problem with pip
```

After executing `pip3 install pithermalcam` i get the above error after a number of hours of waiting for it to complete.

**Comment by tomshaffner** [comment]
This is a problem installing opencv as the error says. There are instructions related to this instead on the instruction page, and if those don't work it's a problem to debug with open cv, not this library.
 
 
  Am Fr., Jan. 13, 2023 at 6:00 schrieb Jonathan ***@***.***>:   


Hi, i am trying to install a python library on my raspberry pi 3 b device and i get this error after waiting a number of hours:
File Edit Tabs Help
Note: class cv::detail: :GraphcutSeamFinder has more than 1 base class (not supported by Python C extensions)
Bases: cv::detail::GraphCutSeamFinderBase, cv::detail::Seanfinder
Only the first base class will be used
98%] Built target gen_opencv_python_source
98x] Building cxx object modules/python3/CMakeFiles/opencv_ python3.dir/_/src2/cv2.cpp.o
c++: fatal error: killed signal terminated program cclplus
compilation terminated.
gmake[2]: "" [ modu les/ python3/CMakeFi les/opencv _ python3.dir/build.make:76: modules/python3/CMakeFi les/opencv _python:
dir/ _ /src2/cv2.cpp.o] Error 1
gmake[1]: """ [CHakeFiles/Nakefile2:2216: modules/ python3/CHakeFi les/opencv_python3.dir/all] Error 2
gmake: """ [Makefile:166: all] Error 2
Traceback (most recent call last):
File "/tmp/pip-build-env-afnllk7p/over lay/ lib/python3.9/ site-packages/skbuild/setuptools_ wrap.py", line 640, in set
cmkr.make(make _args, install_target=cmake_installtarget, env-env)
File "/tmp/pip-build-env-afnllk7p/overlay/ lib/python3.9/site-packages/skbuild/cmaker.py". line 684, in make
self . make _impl(clargs=clargs, config=config, source_ dir=source _dir, installtarget=installtarget, env-env)
File "/tmp/pip-build-env-afnl lk?p/overlay/lib/python3.9/site-packages/skbuild/cmaker.py". line 715. in make_impl
raise SKBuildError(
An error occurred while building with CMake.
Command:
cmake --build . --target install --config Release --
Install target:
install
Source directory:
/tmp/pip-install-3rgbddoa/opencv-python _a5579075d46e4d1a9494966edbd90a64
working directory:
/tmp/pip-install- 3rgbddoa/opencv-python a5579075d4 6e1d1a9494966edbd90a64/ skbui ld/linux-armv7 l-3.9/cmake-bui ld
Please check the install target is valid and see CMake's output for more information.
error: subprocess-exited-with-error
Building wheel for opencv-python (pyproject. toml) did not run successfully.
exit code:
See above for output
note: This error originates from a subprocess, and is likely not a problem with pip

After executing pip3 install pithermalcam i get the above error after a number of hours of waiting for it to complete.

**Comment by jonneymendoza** [comment]
How do i install the opencv? the instructions are very vague on how to do so?

**Comment by tomshaffner** [comment]
You might search the instructions; there's actually a whole section discussing two different ways to install opencv.
Ultimately though, opencv is just a dependency of this library; if installing it via pip is throwing errors, you'll be better off debugging that as a separate issue with opencv and then coming back to this library once it's fixed. If you're getting different behavior on your pi that's causing that to break, that suggests some other conflict or problem between it and your setup and that's not something this library can speak to.
Hope that puts you on the right path to finding a solution.

    On Friday, January 13, 2023 at 02:48:15 PM EST, Jonathan Richards ***@***.***> wrote:  
 
 


How do i install the opencv? the instructions are very vague on how to do so?

**Comment by jonneymendoza** [comment]
the instructions are vague as 2nd step i dont understand:

`Install remaining requirements using either: a. pip3 install the requirements.txt or b. pip3 install the requirements_without_opencv.txt`
