### ISSUE TITLE
Too many retries (bus 0 fwiw)

### ISSUE THREAD

**Issue by bmidgley** [tomshaffner/PiThermalCam#39]
I love the results you've gotten. I wish I could see something similar. I'm using a pi5/4gb and 55 degree MLX90640.

Unfortunately, I burned out i2c bus 1 by wiring it up wrong :/ so I've had to switch to bus 0. It's hardcoded sadly, so I changed my copy.

```
$ diff -u /home/bmidgley/lib/python3.11/site-packages/pithermalcam/pi_therm_cam.py*
--- /home/bmidgley/lib/python3.11/site-packages/pithermalcam/pi_therm_cam.py	2024-11-05 14:55:33.924923128 -0700
+++ /home/bmidgley/lib/python3.11/site-packages/pithermalcam/pi_therm_cam.py.orig	2024-11-05 14:52:50.113668969 -0700
@@ -55,7 +55,7 @@
     def _setup_therm_cam(self):
         """Initialize the thermal camera"""
         # Setup camera
-        self.i2c = busio.I2C(board.D1, board.D0, frequency=800000)  # setup I2C
+        self.i2c = busio.I2C(board.SCL, board.SDA, frequency=800000)  # setup I2C
         self.mlx = adafruit_mlx90640.MLX90640(self.i2c)  # begin MLX90640 with I2C comm
         self.mlx.refresh_rate = adafruit_mlx90640.RefreshRate.REFRESH_8_HZ  # set refresh rate
         time.sleep(0.1)
```

but now it finds the device but won't run:

```
/home/bmidgley/lib/python3.11/site-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py:30: RuntimeWarning: I2C frequency is not settable in python, ignoring!
  warnings.warn(
Camera didn't seem to work properly. Returned the following error:
Traceback (most recent call last):
  File "/home/bmidgley/./ir2.py", line 4, in <module>
    ptc.test_camera()
  File "/home/bmidgley/lib/python3.11/site-packages/pithermalcam/__init__.py", line 25, in test_camera
    raise(e)
  File "/home/bmidgley/lib/python3.11/site-packages/pithermalcam/__init__.py", line 11, in test_camera
    thermcam = pithermalcam()  # Instantiate class
               ^^^^^^^^^^^^^^
  File "/home/bmidgley/lib/python3.11/site-packages/pithermalcam/pi_therm_cam.py", line 50, in __init__
    self.update_image_frame()
  File "/home/bmidgley/lib/python3.11/site-packages/pithermalcam/pi_therm_cam.py", line 227, in update_image_frame
    self._pull_raw_image()
  File "/home/bmidgley/lib/python3.11/site-packages/pithermalcam/pi_therm_cam.py", line 88, in _pull_raw_image
    self.mlx.getFrame(self._raw_image)  # read mlx90640
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bmidgley/lib/python3.11/site-packages/adafruit_mlx90640.py", line 132, in getFrame
    status = self._GetFrameData(mlx90640Frame)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bmidgley/lib/python3.11/site-packages/adafruit_mlx90640.py", line 161, in _GetFrameData
    raise RuntimeError("Too many retries")
RuntimeError: Too many retries
```

**Comment by bmidgley** [comment]
ok I'll just close this. I had spelled out the baudrate incorrectly. On the other bus, it has to look like this:

dtparam=i2c_vc=on,i2c_vc_baudrate=400000

**Comment by shvmm** [comment]
I had this exact issue and specifying out the dtparam=i2c_arm=on,i2c_arm_baudrate=400000 in /boot/firmware/config.txt fixed it for me
